#!/bin/bash
# This is a simple build script, place your post-deploy but pre-start commands
# in this script.  This script gets executed directly, so it could be python,
# php, ruby, etc.

# Ensure a deployments directory exists
mkdir -p ${OPENSHIFT_REPO_DIR}/deployments

# Remove any existing deployment descriptors
rm -f ${OPENSHIFT_REPO_DIR}/deployments/*.clj

# Find the Clojure project and create a deployment descriptor
echo "Deploying tic-tac-doom"

cat <<__EOF__ > ${OPENSHIFT_REPO_DIR}/deployments/tic-tac-doom.clj
{:root "${OPENSHIFT_REPO_DIR}"}
__EOF__

touch ${OPENSHIFT_REPO_DIR}/deployments/tic-tac-doom.clj.dodeploy
