#!/bin/bash
# This is a simple build script, place your post-deploy but pre-start commands
# in this script.  This script gets executed directly, so it could be python,
# php, ruby, etc.

POLYGLOT_VERSION="1.9.0"
IMMUTANT_VERSION="0.6.0"

# These ENV variables have been removed from OpenShift, so we recreate them
# for backwards compatibility for now...
OPENSHIFT_GEAR_DIR="${OPENSHIFT_HOMEDIR}/jbosseap-6.0/"
OPENSHIFT_GEAR_TYPE="jbosseap-6.0"

cd ${OPENSHIFT_DATA_DIR}

# Download and extract Immutant modules
if [ ! -d ${OPENSHIFT_GEAR_DIR}${OPENSHIFT_GEAR_TYPE}/modules/org/immutant ] && [ ! -d immutant-${IMMUTANT_VERSION}-modules ]; then
    curl -Lo immutant-dist-modules.zip "http://torquebox.org/release/org/immutant/immutant-dist/${IMMUTANT_VERSION}/immutant-dist-${IMMUTANT_VERSION}-modules.zip"
    unzip -d immutant-${IMMUTANT_VERSION}-modules immutant-dist-modules.zip
    rm immutant-dist-modules.zip
fi

if [ ! -d ${OPENSHIFT_GEAR_DIR}${OPENSHIFT_GEAR_TYPE}/modules/org/immutant ]; then
    # Symlink Immutant modules into the app's .openshift/config/modules directory
    mkdir -p ${OPENSHIFT_REPO_DIR}/.openshift/config/modules/org
    ln -s ${OPENSHIFT_DATA_DIR}/immutant-${IMMUTANT_VERSION}-modules/modules/org/immutant ${OPENSHIFT_REPO_DIR}/.openshift/config/modules/org/immutant
fi

# Download a Polyglot HASingleton module and extract
if [ ! -d ${OPENSHIFT_GEAR_DIR}${OPENSHIFT_GEAR_TYPE}/modules/org/projectodd/polyglot/hasingleton ] && [ ! -d polyglot-hasingleton-${POLYGLOT_VERSION}-module ]; then
    curl -Lo polyglot-hasingleton-module.zip "http://torquebox.org/release/org/projectodd/polyglot-hasingleton/${POLYGLOT_VERSION}/polyglot-hasingleton-${POLYGLOT_VERSION}-module.zip"
    unzip -d polyglot-hasingleton-${POLYGLOT_VERSION}-module polyglot-hasingleton-module.zip
    rm polyglot-hasingleton-module.zip
fi

if [ ! -d ${OPENSHIFT_GEAR_DIR}${OPENSHIFT_GEAR_TYPE}/modules/org/projectodd/polyglot/hasingleton ]; then
    # Symlink Polyglot HASingleton module into the app's .openshift/config/modules directory
    mkdir -p ${OPENSHIFT_REPO_DIR}/.openshift/config/modules/org/projectodd/polyglot/hasingleton
    ln -s ${OPENSHIFT_DATA_DIR}/polyglot-hasingleton-${POLYGLOT_VERSION}-module ${OPENSHIFT_REPO_DIR}/.openshift/config/modules/org/projectodd/polyglot/hasingleton/main
fi

# Download a Polyglot Cache module and extract
if [ ! -d ${OPENSHIFT_GEAR_DIR}${OPENSHIFT_GEAR_TYPE}/modules/org/projectodd/polyglot/cache ] && [ ! -d polyglot-cache-${POLYGLOT_VERSION}-module ]; then
    curl -Lo polyglot-cache-module.zip "http://torquebox.org/release/org/projectodd/polyglot-cache/${POLYGLOT_VERSION}/polyglot-cache-${POLYGLOT_VERSION}-module.zip"
    unzip -d polyglot-cache-${POLYGLOT_VERSION}-module polyglot-cache-module.zip
    rm polyglot-cache-module.zip
fi

if [ ! -d ${OPENSHIFT_GEAR_DIR}${OPENSHIFT_GEAR_TYPE}/modules/org/projectodd/polyglot/cache ]; then
    # Symlink Polyglot Cache module into the app's .openshift/config/modules directory
    mkdir -p ${OPENSHIFT_REPO_DIR}/.openshift/config/modules/org/projectodd/polyglot/cache
    ln -s ${OPENSHIFT_DATA_DIR}/polyglot-cache-${POLYGLOT_VERSION}-module ${OPENSHIFT_REPO_DIR}/.openshift/config/modules/org/projectodd/polyglot/cache/main
fi

